### PR TITLE
Work with Python 3.9

### PR DESCRIPTION
**Pull request by plotski**

### CODE REVIEW

**Comment by mueslo** [comment]
There are multiple libraries we (indirectly) depend on that do not yet have Python 3.9 compatible versions: `babelfish`, `diskcache`, `boto` and `attrdict`. Maybe some of them already have compatible versions, but they are not fixed by minimum version numbers of packages we depend on. `attrdict` is unmaintained and will not be fixed, so it needs to be fixed manually or replaced.

**Comment by plotski** [comment]
While diskcache doesn't have the "Programming Language :: Python :: 3.9"
classifier, it has "python_requires='>=3' and it seems to work fine. I assume
the 3.9 classifier is only missing because there hasn't been enough testing
yet. Python 3.9 is not a major release and shouldn't break much.

boto doesn't even support Python 3.5, which is pythonBits' minimum version. It
is recommended to use boto3. https://pypi.org/project/boto/
With that said, boto has no hard restrictions on the Python version and seems to
work fine with 3.9.

attrdict seems to support Python 3.*.
https://github.com/bcj/AttrDict/blob/master/setup.py

The downside of refusing to work with 3.9 is that pythonBits becomes useless
when distros upgrade. It's not easy to install multiple Python versions in
parallel, especially for users who aren't Python developers.

The downside of working with 3.9 without 100% support from upstream is that
there may be some bugs. But it's been working perfectly normal for me.

**Comment by mueslo** [comment]
I restricted it because of these warnings:

so either you can still import ABCs from `collections` in Python 3.9, or
the packages fixed this and you were lucky to install a more up to date
version, since you say it works fine in python 3.9 and I know that
`attrdict` is unmaintained, it must be the former. can you confirm?

========================================================= warnings summary
=========================================================
.tox/py38/lib/python3.8/site-packages/babelfish/converters/__init__.py:11
.tox/py38/lib/python3.8/site-packages/babelfish/converters/__init__.py:11:
DeprecationWarning: Using o
r importing the ABCs from 'collections' instead of from 'collections.abc'
is deprecated since Python 3.3, and in 3.9 it will stop wo
rking
   class CaseInsensitiveDict(collections.MutableMapping):

.tox/py38/lib/python3.8/site-packages/diskcache/persistent.py:8
.tox/py38/lib/python3.8/site-packages/diskcache/persistent.py:8:
DeprecationWarning: Using or importin
g the ABCs from 'collections' instead of from 'collections.abc' is
deprecated since Python 3.3, and in 3.9 it will stop working
   from collections import MutableMapping, OrderedDict, Sequence

.tox/py38/lib/python3.8/site-packages/diskcache/persistent.py:9
.tox/py38/lib/python3.8/site-packages/diskcache/persistent.py:9
.tox/py38/lib/python3.8/site-packages/diskcache/persistent.py:9
.tox/py38/lib/python3.8/site-packages/diskcache/persistent.py:9:
DeprecationWarning: Using or importin
g the ABCs from 'collections' instead of from 'collections.abc' is
deprecated since Python 3.3, and in 3.9 it will stop working
   from collections import KeysView, ValuesView, ItemsView

.tox/py38/lib/python3.8/site-packages/boto/plugin.py:40
.tox/py38/lib/python3.8/site-packages/boto/plugin.py:40:
DeprecationWarning: the imp module is depreca
ted in favour of importlib; see the module's documentation for alternative
uses
   import imp

.tox/py38/lib/python3.8/site-packages/attrdict/mapping.py:4
.tox/py38/lib/python3.8/site-packages/attrdict/mapping.py:4:
DeprecationWarning: Using or importing th
e ABCs from 'collections' instead of from 'collections.abc' is deprecated
since Python 3.3, and in 3.9 it will stop working
   from collections import Mapping

**Comment by mueslo** [comment]
ok, it seems this was pushed back a little bit more: https://docs.python.org/3/library/collections.html now states

> Deprecated since version 3.3, will be removed in version 3.10: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.9.

So please update the PR to destrict to versions <3.10

**Comment by plotski** [comment]
Done.

Thanks for figuring this out.

**Comment by mueslo** [comment]
Why <= 3.10 and not < 3.10?

**Comment by plotski** [comment]
Because duuurrrrrrrrrhh... glxfzxiks

Yes. What you said.

**Pull request merged**
